# Project: AI_Process
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o ai1.o
LINKOBJ  = main.o ai1.o
LIBS     = -L"D:/appstudy/Dev-Cpp/MinGW64/lib" -L"D:/appstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/appstudy/Dev-Cpp/MinGW64/include" -I"D:/appstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/appstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/appstudy/Dev-Cpp/MinGW64/include" -I"D:/appstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/appstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/appstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = AI_Process.exe
CXXFLAGS = $(CXXINCS) -g3 -std=c++11
CFLAGS   = $(INCS) -g3 -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

ai1.o: ai1.cpp
	$(CPP) -c ai1.cpp -o ai1.o $(CXXFLAGS)
